GPUS: (0,1)
LOG_DIR: 'log/'
DATA_DIR: ''
OUTPUT_DIR: 'output/'
WORKERS: 4
PRINT_FREQ: 100
COMMENT: 'Experiment_CIFAR_RobustTraining'

MODEL: 
  NAME: mdeq
  NUM_LAYERS: 10
  NUM_CLASSES: 10
  NUM_GROUPS: 8
  DROPOUT: 0.
  F_THRES: 18
  B_THRES: 20
  WNORM: true
  GNORM: true
  DOWNSAMPLE_TIMES: 0
  EXPANSION_FACTOR: 5
  OUTPUT_NL: 'sigmoid'
  JIIO_THRES: 80
  EPSILON: 1.0
  MEM: 20
  PROJ_GD: false
  TRAJ_REG: true
  ALPHA_0:
    - 0.1
    - 0.1
  IMAGE_SIZE: 
    - 3
    - 32
    - 32
  EXTRA:
    FULL_STAGE:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      HEAD_CHANNELS:
      - 8
      - 16
      FINAL_CHANSIZE: 200
      NUM_BLOCKS:
      - 1
      - 1
      NUM_CHANNELS:
      - 24
      - 24
      FUSE_METHOD: SUM
CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
DATASET:
  DATASET: 'cifar10'
  DATA_FORMAT: 'jpg'
  ROOT: 'data/cifar10/'
  TEST_SET: 'val'
  TRAIN_SET: 'train'
  AUGMENT: false
TEST:
  BATCH_SIZE_PER_GPU: 48
  MODEL_FILE: ''
TRAIN:
  JAC_COEFF : 0.01
  BATCH_SIZE_PER_GPU: 48
  BEGIN_EPOCH: 0
  END_EPOCH: 20
  RESUME: false
  LR_SCHEDULER: 'cosine'
  PRETRAIN_STEPS: 20000
  LR_FACTOR: 0.1
  LR_STEP:
  - 30
  - 60
  - 90
  OPTIMIZER: adam
  LR: 0.001
  WD: 0.0000025
  MOMENTUM: 0.9
  NESTEROV: true
  SHUFFLE: true
DEBUG:
  DEBUG: false